services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: spacio
      POSTGRES_PASSWORD: spacio123
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:81"

volumes:
  pgdata:
